numDisparities: 12 #16k
SADWindowSize : 7 #2k+1
uniquenessRatio : 15 #between 5-15 is good
speckleWindowSize : 100 #50-200 range, 0 to disable
speckleRange : 2 #1-2 good, auto multiplication by 16
disp12MaxDiff : 40 #tunable