numDisparities: 8 #16k
SADWindowSize : 1 #2k+1
uniquenessRatio : 10 #between 5-15 is good
speckleWindowSize : 100 #50-200 range, 0 to disable
speckleRange : 2 #1-2 good, auto multiplication by 16
disp12MaxDiff : 1 #tunable
mindisaprity : 0 #can be greater than 0
prefilterCap : 63 #31 or 4
wls_lamda : 8000.00
wls_sigma : 1.5